### ISSUE TITLE
Avviso per Coluccio :-)

### ISSUE THREAD

**Issue by robs05** [lucifero55/SitoBello#1]
Sorry, probabilmente questo non è il miglior metodo per comunicare questa cosa a Coluccio, ma non ho alcun contatto per poterlo fare. @lucifero55 mi potresti fare la cortesia di far recapitare il seguente messaggio a Coluccio: 
"ho risolto quella cosa che stavamo provando oggi, il problema era che sul disco c'erano due copie dello stesso file *.app, bastava cancellare la copia duplicata, la prossima volta provvediamo a creare l'USB bootable".

la soluzione era questa

> To fix this issue you need to delete all copies of "Install OS X xxxxxxx.app" from all mounted volumes and empty the Trash.

Grazie

**Comment by TeoColuccio** [comment]
Prof ci scambiamo le mail? Anche io ho trovato "qualche" soluzione

**Comment by robs05** [comment]
Certo, robs05@hotmail.it
